### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by malvarezg** [t0x3e8/TinyKanbanBoard#1]
Hi @t0x3e8 , 

When i try to compile i get errors because says that following files don't exist:

KanbanApplicationMVVM\Database\KanbanDB.mdf
KanbanApplicationMVVM\Database\KanbanDB_log.ldf
KanbanBoardApplication\Database\BoardsDB.mdf

I don't know if its possible to generate dbs without this files.

Thanks!

**Comment by t0x3e8** [comment]
Hi @malvarezg,
I updated the repository with database. I hope it will work now.
good luck and let me know, how it went.
BR Jarek
